#!/bin/bash

scriptFolder=$(realpath $(dirname $0))

# Handle in-arguments
for i in "$@"
do
    case $i in
        # Cleans up logs, certs, everything.
        -a|--all)
            allFiles=true
            shift # past argument=value
            ;;
    esac
done


# Cleanup virtual network infrastructure
echo "Tearing down virtual network infrastructure. Will ask for password in order to gain root access."
sudo $scriptFolder/net-setup/teardown.bash

if [ "$allFiles" == true ]; then
    # Remove temoporary files
    rm -rf $scriptFolder/certs
    rm -f $scriptFolder/config/netem.Caddyfile
    rm -f $scriptFolder/browser-controller/hostname.py
fi


