#!/bin/bash

scriptFolder=$(realpath $(dirname $0))

# Check if root
if (( $(id -u) != 0 )); then
    echo "The network emulation tool must be run as root."
    exit 1
fi

# Handle in-arguments
for i in "$@"
do
    case $i in
        # Debug mode does not initialize a virtual display
        -d|--debug)
            debugMode=true
            shift # past argument=value
            ;;
    esac
done

# ------------------ RUN


# Setup a webserver of some sort
sudo ip netns exec server-ns nginx -p $(realpath $(dirname .)) -c config/netem.nginx.conf

# Run browser
if [ "$debugMode" != true ]; then
    python3 $scriptFolder/browser-controller/browser-runner.py
else
    python3 $scriptFolder/browser-controller/browser-runner.py --with-gui
fi

# ----------------- TEARDOWN
sleep 5
# Close web server of some sort
kill -QUIT $( cat /tmp/netem.nginx.pid )

