#!/bin/bash

thisFolder=$(realpath $(dirname $0))
selenium=$thisFolder/selenium-server-standalone-3.0.1.jar
logFile=$thisFolder/../logs/netem.selenium.log
pidfile=/tmp/netem.selenium.pid

arg=$1

touch $logFile

if [ ${#arg} -lt 1 ]
    then echo "\nUSAGE: $0 {start|stop}\n"
exit 1
fi

if [ $arg = stop ]
    then selpid=`cat $pidfile` && kill $selpid
echo "Stopping Selenium server!"
exit 0
fi

if [ $arg = start ]
    then java -jar $selenium &> $logFile &
echo "Starting Selenium server!"
sleep 5 # Wait so that Selenium can start properly
echo $! > $pidfile
exit 0
fi
